print("Here is the news on Zelda Breath of the Wild")


print("Zelda Breath of the wild is a intendo swich game that is very popular.")
print("Zelda Breath of The Wild is a fantisy game and involves picking up")
print("food, wepons, armor, shields, hearts and spirt orbs(wich help you get hearts and stamnia)")
print("In Zelda Breath of The Wild you spawn on the great platue")
print("on the great platue you are sposed to let an old man see 4 spirt orbs")
print("then the old man admits he was the king of hyrule and you were his daughter Zelda's knight")
print("then the old man askes you to defeat the bad Ganon guy and save his daughter that is in hyrule castle")
print("and askes you to go to a villige named kakarico. Then at kakriko a old lady who saw you die")
print("said you have to find all the memories of you and Zelda and then come back.")
print("She also askes for you to go to 4 divine beasts and take them back from Ganon.")
print("She tells you that divine beasts are")
print("vah Ruta an elaphant")
print("vah Rudania a lizard")
print("vah Naboris a camel")
print("and vah Medoh a bird")
print("there is also a 5th divine beast that comes with the dlc packs")
print("and a travel madalien in a basment full of gaurdians")
print("and there you go")
